---
name: attu-prod
networks:
    attu:
        attachable: true
        name: attu_prod
services:
    database:
        healthcheck:
            interval: 5s
            retries: 5
            start_period: 5s
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            timeout: 3s
        image: mariadb:lts
        logging:
            driver: journald
        networks:
            - attu
        restart: always
        volumes:
            - ./database:/var/lib/mysql
    job-chron:
        build:
            context: .
            dockerfile: ./mediawiki.Dockerfile
            target: jobrunner
        depends_on:
            job-update:
                condition: service_completed_successfully
        env_file:
            - .env
        environment:
            RUNNER_TYPE: chron
        logging:
            driver: journald
        networks:
            - attu
        restart: always
        volumes:
            - ./images:/var/www/mediawiki/images
            - ./sitemap:/var/www/mediawiki/sitemap
    job-runner:
        build:
            context: .
            dockerfile: ./mediawiki.Dockerfile
            target: jobrunner
        depends_on:
            job-update:
                condition: service_completed_successfully
        env_file:
            - .env
        environment:
            RUNNER_TYPE: runner
        logging:
            driver: journald
        networks:
            - attu
        restart: always
        volumes:
            - ./images:/var/www/mediawiki/images
            - ./sitemap:/var/www/mediawiki/sitemap
    job-update:
        build:
            context: .
            dockerfile: ./mediawiki.Dockerfile
            target: jobrunner
        depends_on:
            database:
                condition: service_healthy
            redis:
                condition: service_healthy
        env_file:
            - .env
        environment:
            RUNNER_TYPE: update
        logging:
            driver: journald
        networks:
            - attu
        restart: 'no'
        volumes:
            - ./images:/var/www/mediawiki/images
            - ./sitemap:/var/www/mediawiki/sitemap
    mediawiki:
        build:
            context: .
            dockerfile: ./mediawiki.Dockerfile
        command: bash -c "php maintenance/run.php update --quick; exec php-fpm"
        depends_on:
            job-update:
                condition: service_completed_successfully
        env_file:
            - .env
        logging:
            driver: journald
        networks:
            - attu
        restart: always
        scale: 2
        volumes:
            - ./images:/var/www/mediawiki/images
            - ./sitemap:/var/www/mediawiki/sitemap
    nginx:
        build:
            context: .
            dockerfile: ./nginx.Dockerfile
        depends_on:
            - mediawiki
        environment:
            BUILD_TYPE: prod
        logging:
            driver: journald
        networks:
            - attu
        ports:
            - 127.0.0.1:6010:80
        restart: always
        volumes:
            - ./files/listed_ip_30_all.txt:/var/www/mediawiki/resources/listed_ip_30_all.txt
            - ./images:/var/www/mediawiki/images
            - ./sitemap:/var/www/mediawiki/sitemap
    redis:
        command: ["redis-server", "--save", "60",  "1", "--loglevel", "warning"]
        healthcheck:
            interval: 5s
            retries: 5
            start_period: 5s
            test: ["CMD", "redis-cli", "ping"]
            timeout: 3s
        image: redis:8
        logging:
            driver: journald
        mem_limit: 1024m
        networks:
            - attu
        restart: always
        volumes:
            - redis-data-prod:/data
    yourls:
        depends_on:
            database:
                condition: service_healthy
        env_file:
            - .env
        environment:
            YOURLS_DB_HOST: database
            YOURLS_DB_NAME: attu_links
            YOURLS_DB_USER: attu
            YOURLS_SITE: https://links.attuproject.org
            YOURLS_USER: doom
        image: yourls:latest
        logging:
            driver: journald
        networks:
            - attu
        ports:
            - 127.0.0.1:6009:8080
        restart: always
        volumes:
            - ./files/assets/favicon.ico:/var/www/mediawiki/favicon.ico
            - ./files/remoteip.load:/etc/apache2/mods-enabled/remoteip.load
            - ./files/well-known:/var/www/mediawiki/.well-known
volumes:
    redis-data-prod:
