name: attu-dev

services:
    mediawiki:
        container_name: attu-mediawiki-dev
        build:
            context: .
            dockerfile: ./mediawiki.Dockerfile
        restart: always
        command: bash -c "php maintenance/run.php update --quick && exec php-fpm"
        links:
            - database
            - memcached
        volumes:
            - ./images:/var/www/mediawiki/images
            - ./sitemap:/var/www/mediawiki/sitemap
          # - ./logs:/var/log/mediawiki
        environment:
            ATTU_DEV_MODE: 1
        env_file:
            - .env
        logging:
            driver: journald

    nginx:
        container_name: attu-nginx-dev
        restart: always
        environment:
            BUILD_TYPE: 'dev'
            ATTU_DEV_MODE: 1
        ports:
            - 127.0.0.1:6008:80
        volumes:
            - ./files/listed_ip_30_all.txt:/var/www/mediawiki/resources/listed_ip_30_all.txt
            - ./images:/var/www/mediawiki/images
            - ./sitemap:/var/www/mediawiki/sitemap
        links:
            - mediawiki
        build:
            context: .
            dockerfile: ./nginx.Dockerfile
        logging:
            driver: journald

    memcached:
        container_name: attu-memcached-dev
        image: memcached:latest
        restart: always
        mem_limit: 768m
        command:
            - --memory-limit=512
        logging:
            driver: journald

    database:
        container_name: attu-database-dev
        image: mariadb:latest
        restart: always
        logging:
            driver: journald
        environment:
            MARIADB_RANDOM_ROOT_PASSWORD: true
            MARIADB_DATABASE: 'attu_wiki'
            MARIADB_USER: 'attu'
        env_file:
            - .env
        volumes:
            - ./attu-wiki-backup_2025-06-30.sql:/docker-entrypoint-initdb.d/init.sql
