---
name: attu-prod
networks:
    attu:
        external: true
        name: attu_unified
services:
    database:
        container_name: attu-database-prod
        healthcheck:
            interval: 10s
            retries: 3
            start_period: 10s
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            timeout: 5s
        image: mariadb:lts
        logging:
            driver: journald
        networks:
            - attu
        restart: always
        volumes:
            - ./database:/var/lib/mysql
    mediawiki:
        build:
            context: .
            dockerfile: ./mediawiki.Dockerfile
        command: bash -c "php maintenance/run.php update --quick; exec php-fpm"
        container_name: attu-mediawiki-prod
        depends_on:
            database:
                condition: service_healthy
        env_file:
            - .env
        logging:
            driver: journald
        networks:
            - attu
        restart: always
        volumes:
            - ./images:/var/www/mediawiki/images
            - ./sitemap:/var/www/mediawiki/sitemap
    memcached:
        command:
            - '--memory-limit=512'
        container_name: attu-memcached-prod
        image: memcached:latest
        logging:
            driver: journald
        mem_limit: 768m
        networks:
            - attu
        restart: always
    nginx:
        build:
            context: .
            dockerfile: ./nginx.Dockerfile
        container_name: attu-nginx-prod
        environment:
            BUILD_TYPE: prod
        logging:
            driver: journald
        networks:
            - attu
        ports:
            - 127.0.0.1:6010:80
        restart: always
        volumes:
            - ./files/listed_ip_30_all.txt:/var/www/mediawiki/resources/listed_ip_30_all.txt
            - ./images:/var/www/mediawiki/images
            - ./sitemap:/var/www/mediawiki/sitemap
    yourls:
        container_name: attu-yourls-prod
        env_file:
            - .env
        environment:
            YOURLS_DB_HOST: attu-database-prod
            YOURLS_DB_NAME: attu_links
            YOURLS_DB_USER: attu
            YOURLS_SITE: https://links.attuproject.org
            YOURLS_USER: doom
        image: yourls:latest
        logging:
            driver: journald
        networks:
            - attu
        ports:
            - 127.0.0.1:6009:8080
        restart: always
        volumes:
            - ./files/assets/favicon.ico:/var/www/mediawiki/favicon.ico
            - ./files/remoteip.load:/etc/apache2/mods-enabled/remoteip.load
            - ./files/well-known:/var/www/mediawiki/.well-known
