---
name: attu-dev
networks:
    attu:
        attachable: true
        name: attu_dev
services:
    database:
        env_file:
            - .env
        environment:
            - MARIADB_DATABASE=attu_wiki
            - MARIADB_RANDOM_ROOT_PASSWORD=true
            - MARIADB_USER=attu
            - MARIADB_PASSWORD=${ATTU_DB_PASSWORD}
        healthcheck:
            interval: 5s
            retries: 5
            start_period: 5s
            test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
            timeout: 3s
        image: mariadb:lts
        logging:
            driver: journald
        networks:
            - attu
        restart: always
        volumes:
            - ./attu-wiki-backup.sql:/docker-entrypoint-initdb.d/init.sql
    job-chron:
        build:
            context: .
            dockerfile: ./mediawiki.Dockerfile
            target: jobrunner
        depends_on:
            job-update:
                condition: service_completed_successfully
        env_file:
            - .env
        environment:
            - RUNNER_TYPE=chron
        logging:
            driver: journald
        networks:
            - attu
        restart: always
        volumes:
            - ./devel/NovaDiscord:/app/mediawiki/extensions/NovaDiscord
            - ./images:/app/mediawiki/images
            - ./sitemap:/app/mediawiki/sitemap
    job-runner:
        build:
            context: .
            dockerfile: ./mediawiki.Dockerfile
            target: jobrunner
        depends_on:
            job-update:
                condition: service_completed_successfully
        env_file:
            - .env
        environment:
            - RUNNER_TYPE=runner
        logging:
            driver: journald
        networks:
            - attu
        restart: always
        volumes:
            - ./devel/NovaDiscord:/app/mediawiki/extensions/NovaDiscord
            - ./images:/app/mediawiki/images
            - ./sitemap:/app/mediawiki/sitemap
    job-update:
        build:
            context: .
            dockerfile: ./mediawiki.Dockerfile
            target: jobrunner
        depends_on:
            database:
                condition: service_healthy
            redis:
                condition: service_healthy
        env_file:
            - .env
        environment:
            - RUNNER_TYPE=update
        logging:
            driver: journald
        networks:
            - attu
        restart: 'no'
        volumes:
            - ./devel/NovaDiscord:/app/mediawiki/extensions/NovaDiscord
            - ./images:/app/mediawiki/images
            - ./sitemap:/app/mediawiki/sitemap
    mediawiki:
        build:
            context: .
            dockerfile: ./mediawiki.Dockerfile
            target: fpm
        depends_on:
            job-update:
                condition: service_completed_successfully
        env_file:
            - .env
        environment:
            - BUILD_TYPE=dev
        logging:
            driver: journald
        networks:
            - attu
        restart: always
        scale: 1
        volumes:
            - ./devel/NovaDiscord:/app/mediawiki/extensions/NovaDiscord
            - ./images:/app/mediawiki/images
            - ./sitemap:/app/mediawiki/sitemap
    nginx:
        build:
            context: .
            dockerfile: ./nginx.Dockerfile
        depends_on:
            - mediawiki
        environment:
            - BUILD_TYPE=dev
        logging:
            driver: journald
        networks:
            - attu
        ports:
            - 127.0.0.1:6008:80
        restart: always
        volumes:
            - ./files/listed_ip_30_all.txt:/app/mediawiki/resources/listed_ip_30_all.txt
            - ./images:/app/mediawiki/images
            - ./sitemap:/app/mediawiki/sitemap
    redis:
        command: [ "redis-server", "--loglevel", "warning" ]
        healthcheck:
            interval: 5s
            retries: 5
            start_period: 5s
            test: [ "CMD", "redis-cli", "ping" ]
            timeout: 3s
        image: redis:8
        logging:
            driver: journald
        mem_limit: 1024m
        networks:
            - attu
        restart: always
