name: attu-prod

services:
    mediawiki:
        container_name: attu-mediawiki-prod
        build:
            context: .
            dockerfile: ./mediawiki.Dockerfile
        command: bash -c "php maintenance/run.php update --quick && exec php-fpm"
        restart: always
        volumes:
            - ./images:/var/www/mediawiki/images
            - ./sitemap:/var/www/mediawiki/sitemap
        env_file:
            - .env
        logging:
            driver: journald
        networks:
            - attu

    nginx:
        container_name: attu-nginx-prod
        restart: always
        environment:
            BUILD_TYPE: 'prod'
        ports:
            - 127.0.0.1:6010:80
        volumes:
            - ./files/listed_ip_30_all.txt:/var/www/mediawiki/resources/listed_ip_30_all.txt
            - ./images:/var/www/mediawiki/images
            - ./sitemap:/var/www/mediawiki/sitemap
        build:
            context: .
            dockerfile: ./nginx.Dockerfile
        logging:
            driver: journald
        networks:
            - attu

    memcached:
        container_name: attu-memcached-prod
        image: memcached:latest
        restart: always
        mem_limit: 768m
        command:
            - --memory-limit=512
        logging:
            driver: journald
        networks:
            - attu

    yourls:
        container_name: attu-yourls-prod
        image: yourls:latest
        restart: always
        ports:
            - 127.0.0.1:6009:80
        environment:
            YOURLS_DB_HOST: 'attu-database-prod'
            YOURLS_DB_USER: 'attu'
            YOURLS_DB_NAME: 'attu_links'
            YOURLS_SITE: https://links.attuproject.org
            YOURLS_USER: 'doom'
        env_file:
            - .env
        volumes:
            - ./files/assets/favicon.ico:/var/www/mediawiki/favicon.ico
            - ./files/remoteip.load:/etc/apache2/mods-enabled/remoteip.load
            - ./files/well-known:/var/www/mediawiki/.well-known
        logging:
            driver: journald
        networks:
            - attu

    database:
        container_name: attu-database-prod
        image: mariadb:latest
        restart: always
        logging:
            driver: journald
        volumes:
            - ./database:/var/lib/mysql
        networks:
            - attu

networks:
    attu:
        external: true
        name: attu_unified
