---
name: attu-dev
services:
    database:
        container_name: attu-database-dev
        env_file:
            - .env
        environment:
            MARIADB_DATABASE: attu_wiki
            MARIADB_RANDOM_ROOT_PASSWORD: true
            MARIADB_USER: attu
        healthcheck:
            interval: 10s
            retries: 3
            start_period: 10s
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            timeout: 5s
        image: mariadb:lts
        logging:
            driver: journald
        restart: always
        volumes:
            - ./attu-wiki-backup.sql:/docker-entrypoint-initdb.d/init.sql
    mediawiki:
        build:
            context: .
            dockerfile: ./mediawiki.Dockerfile
        command: bash -c "php maintenance/run.php update --quick; exec php-fpm"
        container_name: attu-mediawiki-dev
        depends_on:
            database:
                condition: service_healthy
        env_file:
            - .env
        environment:
            ATTU_DEV_MODE: 1
        logging:
            driver: journald
        restart: always
        volumes:
            - ./images:/var/www/mediawiki/images
            - ./sitemap:/var/www/mediawiki/sitemap
    redis:
        command: ["redis-server", "--appendonly", "yes"]
        container_name: attu-redis-dev
        image: redis:7-alpine
        logging:
            driver: journald
        mem_limit: 1024m
        restart: always
        volumes:
            - redis-data-dev:/data
    nginx:
        build:
            context: .
            dockerfile: ./nginx.Dockerfile
        container_name: attu-nginx-dev
        environment:
            ATTU_DEV_MODE: 1
            BUILD_TYPE: dev
        logging:
            driver: journald
        ports:
            - 127.0.0.1:6008:80
        restart: always
        volumes:
            - ./files/listed_ip_30_all.txt:/var/www/mediawiki/resources/listed_ip_30_all.txt
            - ./images:/var/www/mediawiki/images
            - ./sitemap:/var/www/mediawiki/sitemap
volumes:
    redis-data-dev:
