[tool.ruff]
exclude = ["scripts/.venv/", "*.wip.py", "devel/"]
target-version = "py313"
line-length = 320

[tool.ruff.lint]
select = [
  # "E4",
  # "E7",
  # "E9",
  "E",
  "F",
  "Q",
  "W",
  "I",
  "UP",
  "ASYNC",
  "S",
  "A",
  "COM",
  "SIM",
  "PTH",
  "PL",
  "RUF"
]

# select = ["ALL"]
ignore = [
  "E501",     # line-length violations
  "PLR2004",  # magic values
  "PLE1205",  # logging builtin
  "RUF012",   # ClassVar decorators
  "S311",     # random not for crypto
]

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false

[tool.ruff.lint.isort]
# Use a single line after each import block.
lines-after-imports = 1

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.basedpyright]
pythonPlatform = "Linux"
typeCheckingMode = "standard"
reportOptionalOperand = false
reportOptionalMemberAccess = false
reportOptionalSubscript = false
reportInvalidCast = false
reportFunctionMemberAccess = false
reportAttributeAccessIssue = false
reportUnknownMemberType = false
exclude = ["scripts/.venv/", "*.wip.py", "devel/"]

